# Leaked by https://t.me/leak_mine
# Сурцы плагина были слиты телеграмм каналом https://t.me/leak_mine

furnaces:
    # Печки (Можно добавить печек сколько угодно (кастомно))
    speedFurnace:
        name: '&6Еб*нутая печка'
        lore:
            - '&e|&f------------'
            - '&e|'
            - '&e| &6Плавит быстрее чем обычная печка.'
            - '&e|'
            - '&e|&f------------'
        cooktime: 2 # В 2 раза быстрее будет плавить печка
        enchant: true # Сделать чтобы печка зачарована в руке (тип зачарования будет скрыт)
    doubleFurnace:
        name: '&6Двойное проникновение (с смазкой)'
        lore:
            - '&e|&f------------'
            - '&e|'
            - '&e| &6Плавит в 2 раза больше руды. (&c16 алмазов руды = 32 алмаза&6)'
            - '&e|'
            - '&e|&f------------'
        result: 2 # В 2 раза больше ресуров будет приносить печка
        enchant: true # Сделать чтобы печка зачарована в руке (тип зачарования будет скрыт)
    smeltFurnace:
        name: '&6Долго-дрочливая печка (без смазки)'
        lore:
            - '&e|&f------------'
            - '&e|'
            - '&e| &6Плавит в 2 раза меньше топливо.'
            - '&e|'
            - '&e|&f------------'
        burntime: 2 # В 2 раза дольше будет плавиться топливо
        enchant: true # Сделать чтобы печка зачарована в руке (тип зачарования будет скрыт)
        
messages:
    prefix: '&dПечки &f> '
    no-permission: 'У вас нет прав.;title:&dПечки %nl% У вас нет прав.'
    command-notfound: 'Неизвестная команда.'
    give:
        usage: '&c/wfurnace give <игрок> <печь> &f- Выдать игроку печку'
        player-null: 'Игрок не найден.'
        furnace-null: 'Печка не найдена.'
        complete: 'Печка успешно выдана, игроку &c%player%'
    list:
        usage: '&c/wfurnace list &f- Список печей'
        title: 'Список печек:'
        format: '&c%step%&f. %name%'
            
